<?php

use App\Http\Controllers\Trainer\Courses\CourseController as TrainerCourseController;
use App\Http\Controllers\Trainer\Courses\CourseMediaController;
use App\Http\Controllers\Trainer\AcademyAiController;
use App\Http\Controllers\Trainer\CourseCreationController;
use App\Http\Controllers\Trainer\CourseReviewController;
use App\Http\Controllers\Trainer\AnalyticsController;
use App\Http\Controllers\Trainer\DashboardController as TrainerDashboardController;
use App\Http\Controllers\Trainer\SalesController;
use App\Http\Controllers\Trainer\CommerceController;
use App\Http\Controllers\Trainer\StudentsController;
use App\Http\Controllers\Trainer\TutorSettingsController;
use App\Http\Controllers\Trainer\StripeConnectController;
use App\Http\Controllers\Trainer\PageBuilderController;
use App\Http\Controllers\Trainer\AssessmentController;
use App\Http\Controllers\Trainer\AssignmentController;
use App\Http\Controllers\Trainer\CompletionController;
use App\Http\Controllers\Trainer\LearningAccessController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified', 'role:trainer|admin|super-admin'])->prefix('trainer')->name('trainer.')->group(function () {
    Route::get('dashboard', [TrainerDashboardController::class, 'index'])->name('dashboard');
    Route::get('pages', [PageBuilderController::class, 'index'])->middleware('feature:pages')->name('pages.index');
    Route::post('pages', [PageBuilderController::class, 'store'])->middleware('feature:pages')->name('pages.store');
    Route::get('pages/{page}/edit', [PageBuilderController::class, 'edit'])->middleware('feature:pages')->name('pages.edit');
    Route::patch('pages/{page}', [PageBuilderController::class, 'update'])->middleware('feature:pages')->name('pages.update');
    Route::delete('pages/{page}', [PageBuilderController::class, 'destroy'])->middleware('feature:pages')->name('pages.destroy');
    Route::post('pages/{page}/publish', [PageBuilderController::class, 'publish'])->middleware('feature:pages')->name('pages.publish');
    Route::post('pages/{page}/unpublish', [PageBuilderController::class, 'unpublish'])->middleware('feature:pages')->name('pages.unpublish');
    Route::get('pages/{page}/preview', [PageBuilderController::class, 'preview'])->middleware('feature:pages')->name('pages.preview');
    Route::post('pages/{page}/sections', [PageBuilderController::class, 'storeSection'])->middleware('feature:pages')->name('pages.sections.store');
    Route::patch('pages/{page}/sections/{section}', [PageBuilderController::class, 'updateSection'])->middleware('feature:pages')->name('pages.sections.update');
    Route::delete('pages/{page}/sections/{section}', [PageBuilderController::class, 'destroySection'])->middleware('feature:pages')->name('pages.sections.destroy');
    Route::post('pages/{page}/sections/reorder', [PageBuilderController::class, 'reorderSections'])->middleware('feature:pages')->name('pages.sections.reorder');
    Route::get('students', [StudentsController::class, 'index'])->name('students.index');
    Route::get('sales', [SalesController::class, 'index'])->middleware('feature:sales')->name('sales.index');
    Route::post('sales/offers', [CommerceController::class, 'storeOffer'])->middleware('feature:sales')->name('sales.offers.store');
    Route::patch('sales/offers/{offer}/toggle', [CommerceController::class, 'toggleOffer'])->middleware('feature:sales')->name('sales.offers.toggle');
    Route::post('sales/coupons', [CommerceController::class, 'storeCoupon'])->middleware('feature:sales')->name('sales.coupons.store');
    Route::patch('sales/coupons/{coupon}/toggle', [CommerceController::class, 'toggleCoupon'])->middleware('feature:sales')->name('sales.coupons.toggle');
    Route::post('sales/affiliates', [CommerceController::class, 'storeAffiliate'])->middleware('feature:sales')->name('sales.affiliates.store');
    Route::patch('sales/affiliates/{affiliate}/toggle', [CommerceController::class, 'toggleAffiliate'])->middleware('feature:sales')->name('sales.affiliates.toggle');
    Route::post('sales/orders/{order}/refund', [CommerceController::class, 'refund'])->middleware('feature:sales')->name('sales.orders.refund');
    Route::get('analytics', [AnalyticsController::class, 'index'])->name('analytics.index');
    Route::get('academy-ai', [AcademyAiController::class, 'index'])->middleware('feature:ai')->name('academy-ai.index');
    Route::get('academy-ai/course-creation', [CourseCreationController::class, 'index'])->middleware('feature:ai')->name('course-creation.index');
    Route::post('academy-ai/course-creation', [CourseCreationController::class, 'start'])->middleware('feature:ai')->name('course-creation.start');
    Route::post('academy-ai/course-creation/{run}/advance', [CourseCreationController::class, 'advance'])->middleware('feature:ai')->name('course-creation.advance');
    Route::post('academy-ai/course-creation/{run}/retry', [CourseCreationController::class, 'retry'])->middleware('feature:ai')->name('course-creation.retry');

    Route::get('academy-ai/course-creation/{run}/review', [CourseReviewController::class, 'show'])->middleware('feature:ai')->name('course-review.show');
    Route::post('academy-ai/course-creation/{run}/review/proposals', [CourseReviewController::class, 'propose'])->middleware('feature:ai')->name('course-review.propose');
    Route::post('academy-ai/course-creation/{run}/review/proposals/{proposal}/accept', [CourseReviewController::class, 'accept'])->middleware('feature:ai')->name('course-review.accept');
    Route::post('academy-ai/course-creation/{run}/review/proposals/{proposal}/reject', [CourseReviewController::class, 'reject'])->middleware('feature:ai')->name('course-review.reject');
    Route::post('academy-ai/course-creation/{run}/review/publish', [CourseReviewController::class, 'publish'])->middleware('feature:ai')->name('course-review.publish');
    Route::post('academy-ai/run', [AcademyAiController::class, 'run'])->middleware('feature:ai')->name('academy-ai.run');
    Route::post('academy-ai/runs/{run}/apply', [AcademyAiController::class, 'apply'])->middleware('feature:ai')->name('academy-ai.runs.apply');
    Route::get('ai-tutor', [TutorSettingsController::class, 'index'])->middleware('feature:tutor')->name('tutor.index');
    Route::patch('ai-tutor', [TutorSettingsController::class, 'update'])->middleware('feature:tutor')->name('tutor.update');
    Route::post('ai-tutor/courses/{course}/reindex', [TutorSettingsController::class, 'reindex'])->middleware('feature:tutor')->name('tutor.reindex');
    Route::post('courses/{course}/generate-image', [CourseMediaController::class, 'generateImage'])->middleware('feature:ai')->name('courses.generate-image');
    Route::post('lessons/{lesson}/generate-audio', [CourseMediaController::class, 'generateAudio'])->middleware('feature:ai')->name('lessons.generate-audio');
    Route::get('courses/{course}/assessments', [AssessmentController::class, 'index'])->middleware('feature:assessments')->name('assessments.index');
    Route::post('courses/{course}/assessments', [AssessmentController::class, 'store'])->middleware('feature:assessments')->name('assessments.store');
    Route::patch('courses/{course}/assessments/{assessment}', [AssessmentController::class, 'update'])->middleware('feature:assessments')->name('assessments.update');
    Route::delete('courses/{course}/assessments/{assessment}', [AssessmentController::class, 'destroy'])->middleware('feature:assessments')->name('assessments.destroy');
    Route::patch('courses/{course}/assessments/{assessment}/toggle', [AssessmentController::class, 'toggle'])->middleware('feature:assessments')->name('assessments.toggle');

    Route::get('courses/{course}/assignments', [AssignmentController::class, 'index'])->middleware('feature:assignments')->name('assignments.index');
    Route::post('courses/{course}/assignments', [AssignmentController::class, 'store'])->middleware('feature:assignments')->name('assignments.store');
    Route::patch('courses/{course}/assignments/{assignment}', [AssignmentController::class, 'update'])->middleware('feature:assignments')->name('assignments.update');
    Route::delete('courses/{course}/assignments/{assignment}', [AssignmentController::class, 'destroy'])->middleware('feature:assignments')->name('assignments.destroy');
    Route::patch('courses/{course}/assignments/{assignment}/toggle', [AssignmentController::class, 'toggle'])->middleware('feature:assignments')->name('assignments.toggle');
    Route::post('courses/{course}/assignments/{assignment}/submissions/{submission}/review', [AssignmentController::class, 'review'])->middleware('feature:assignments')->name('assignments.review');
    Route::get('courses/{course}/assignments/{assignment}/files/{file}', [AssignmentController::class, 'download'])->middleware('feature:assignments')->name('assignments.files.download');
    Route::get('courses/{course}/completion', [CompletionController::class, 'show'])->middleware('feature:completion')->name('completion.show');
    Route::put('courses/{course}/completion', [CompletionController::class, 'update'])->middleware('feature:completion')->name('completion.update');
    Route::post('courses/{course}/certificates/{certificate}/revoke', [CompletionController::class, 'revoke'])->middleware(['feature:completion', 'feature:certificates'])->name('certificates.revoke');
    Route::get('courses/{course}/learning-access', [LearningAccessController::class, 'index'])->middleware('feature:drip')->name('learning-access.index');
    Route::post('courses/{course}/learning-access', [LearningAccessController::class, 'store'])->middleware('feature:drip')->name('learning-access.store');
    Route::patch('courses/{course}/learning-access/{rule}', [LearningAccessController::class, 'update'])->middleware('feature:drip')->name('learning-access.update');
    Route::delete('courses/{course}/learning-access/{rule}', [LearningAccessController::class, 'destroy'])->middleware('feature:drip')->name('learning-access.destroy');
    Route::resource('courses', TrainerCourseController::class)->except(['show']);
    Route::patch('courses/{course}/status', [TrainerCourseController::class, 'toggleStatus'])->name('courses.toggle-status');

    Route::get('stripe-connect', [StripeConnectController::class, 'edit'])->name('stripe-connect.edit');
    Route::get('stripe-connect/onboard', [StripeConnectController::class, 'onboard'])->name('stripe-connect.onboard');
    Route::get('stripe-connect/return', [StripeConnectController::class, 'return'])->name('stripe-connect.return');
    Route::delete('stripe-connect', [StripeConnectController::class, 'disconnect'])->name('stripe-connect.disconnect');
});
