import { Head, Link, router, useForm } from '@inertiajs/react';
import { ArrowLeft, CheckCircle2, FileText, RotateCcw } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

type Submission = { id:number; version:number; status:'submitted'|'changes_requested'|'approved'; textContent:string|null; linkUrl:string|null; scorePercent:number|null; feedback:string|null; submittedAt:string|null; reviewedAt:string|null; files:Array<{id:number;name:string;url:string}> };
type Props = { course:{id:number;title:string}; assignment:{id:number;title:string;instructions:string;kind:string;deliverableType:'text'|'link'|'file'|'mixed';rubric:Array<{id:number;criterion:string;description:string|null;maxPoints:number}>}; latestSubmission:Submission|null; history:Submission[] };

export default function StudentAssignment({ course, assignment, latestSubmission, history }: Props) {
    const form = useForm<{text_content:string;link_url:string;files:File[]}>({ text_content:'', link_url:'', files:[] });
    const canSubmit = !latestSubmission || latestSubmission.status === 'changes_requested';
    return <><Head title={assignment.title} /><div className="mx-auto max-w-4xl space-y-6 px-4 py-6 sm:px-6">
        <Button variant="ghost" asChild className="rounded-full"><Link href={`/student/courses/${course.id}`}><ArrowLeft className="size-4" /> {course.title}</Link></Button>
        <section className="academy-panel rounded-2xl p-5 sm:p-7"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{assignment.kind}</Badge><Badge variant="secondary">{assignment.deliverableType}</Badge></div><h1 className="mt-4 text-2xl font-semibold">{assignment.title}</h1><p className="mt-4 whitespace-pre-wrap leading-7 text-muted-foreground">{assignment.instructions}</p><div className="mt-6 rounded-xl bg-bg-soft p-4"><h2 className="font-semibold">Rubric</h2><div className="mt-3 space-y-3">{assignment.rubric.map((item)=><div key={item.id} className="flex justify-between gap-4 text-sm"><div><p className="font-medium">{item.criterion}</p>{item.description && <p className="text-muted-foreground">{item.description}</p>}</div><span>{item.maxPoints} pts</span></div>)}</div></div></section>
        {latestSubmission && <section className="academy-panel rounded-2xl p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Dernier rendu · v{latestSubmission.version}</h2><Badge>{latestSubmission.status}</Badge></div>{latestSubmission.scorePercent!==null && <p className="mt-3 text-2xl font-semibold">{latestSubmission.scorePercent}%</p>}{latestSubmission.feedback && <div className="mt-3 rounded-xl bg-bg-soft p-4"><p className="text-sm font-medium">Feedback du formateur</p><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{latestSubmission.feedback}</p></div>}{latestSubmission.status==='approved' && <p className="mt-3 flex items-center gap-2 text-sm text-emerald-700"><CheckCircle2 className="size-4" /> Travail approuvé.</p>}{latestSubmission.status==='changes_requested' && <p className="mt-3 flex items-center gap-2 text-sm"><RotateCcw className="size-4" /> Une nouvelle version peut être envoyée.</p>}</section>}
        {canSubmit && <section className="academy-panel space-y-4 rounded-2xl p-5"><h2 className="font-semibold">{latestSubmission ? 'Envoyer une nouvelle version' : 'Envoyer mon rendu'}</h2>{(['text','mixed'].includes(assignment.deliverableType)) && <div><Label>Texte</Label><Textarea className="min-h-36" value={form.data.text_content} onChange={(e)=>form.setData('text_content',e.target.value)} /></div>}{(['link','mixed'].includes(assignment.deliverableType)) && <div><Label>Lien</Label><Input type="url" value={form.data.link_url} onChange={(e)=>form.setData('link_url',e.target.value)} /></div>}{(['file','mixed'].includes(assignment.deliverableType)) && <div><Label>Fichiers privés</Label><Input type="file" multiple onChange={(e)=>form.setData('files',Array.from(e.target.files ?? []))} /></div>}<Button disabled={form.processing} onClick={()=>form.post(`/student/courses/${course.id}/assignments/${assignment.id}`,{forceFormData:true,preserveScroll:true})}>Envoyer</Button></section>}
        {history.length>1 && <section className="space-y-2"><h2 className="font-semibold">Historique</h2>{history.map((item)=><div key={item.id} className="rounded-xl border p-3 text-sm"><div className="flex justify-between"><span>Version {item.version}</span><Badge variant="outline">{item.status}</Badge></div><div className="mt-2 flex flex-wrap gap-2">{item.files.map((file)=><Button key={file.id} size="sm" variant="outline" asChild><a href={file.url}><FileText className="size-3.5" /> {file.name}</a></Button>)}</div></div>)}</section>}
    </div></>;
}
